// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCptMXTx1biTB3-0WxTmlJQHf1u-3DOGA',
    appId: '1:96421652599:android:a46f139e504ebf4e1dbe72',
    messagingSenderId: '96421652599',
    projectId: 'royal-2022',
    storageBucket: 'royal-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtEne3QFvTHpKB8_XoqFhimhFiYvuhL1g',
    appId: '1:96421652599:ios:4595733fff1a7b321dbe72',
    messagingSenderId: '96421652599',
    projectId: 'royal-2022',
    storageBucket: 'royal-2022.appspot.com',
    androidClientId: '96421652599-pp33b6j2m7iqo153guvbldk6bsjqmmek.apps.googleusercontent.com',
    iosClientId: '96421652599-ul23msrsd35m7126ip910v1o3fapkkjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.royalMarketing',
  );
}
